<?php

/**
 * @file
 * Base module file.
 */

/**
 * Implements hook_tester_info() {
 */
function tester_tester_info() {
  $items['system'] = array(
    'description' => 'Testing base system URLs.',
    'module' => 'tester',
    'dependencies' => array(),
  );
  $items['menu'] = array(
    'description' => 'Testing menu items.',
    'module' => 'tester',
    'dependencies' => array('menu'),
  );
  $items['node'] = array(
    'description' => 'Testing node pages.',
    'module' => 'tester',
    'dependencies' => array('node'),
  );
  $items['user'] = array(
    'description' => 'Testing user pages.',
    'module' => 'tester',
    'dependencies' => array('user'),
  );
  return $items;
}
