<?php

/**
 * @file
 * Base module file.
 */

/**
 * Implements hook_tester_info() {
 */
function tester_tester_info() {
  $items['system'] = array(
    'description' => 'Testing base system URLs.',
    'module' => 'tester',
    'dependencies' => array(),
  );
  $items['node'] = array(
    'description' => 'Testing node pages.',
    'module' => 'tester',
    'dependencies' => array('node'),
  );
  return $items;
}


/**
 * Implements hook_tester_crawl().
 */
function tester_tester_crawl($path) {
  // TODO: Return an array instead?
  drush_print('Testing home page.');


  drush_print('Test 404 page');
  $data = drupal_http_request($path . '/asdkjh234213h123asdasd');
  drush_print($path . '/asdkjh234213h123asdasd');

  drush_print('Testing node paths.');
  $nodes = db_query("SELECT nid FROM {node} WHERE status > 0")->fetchAll();
  foreach ($nodes as $node) {
    drush_print($path . url("node/$node->nid"));
    $data = drupal_http_request($path . url("node/$node->nid"));
  }

  drush_print('Testing user paths.');
  $users = db_query("SELECT uid FROM {users} WHERE status > 0")->fetchAll();
  foreach ($users as $user) {
    drush_print($path . url("user/$user->uid"));
    $data = drupal_http_request($path . url("user/$user->uid"));
  }

}
