<?php

namespace Drupal\tester\Annotation;

use Drupal\Component\Annotation\Plugin;

/**
 * Defines a TesterPlugin type annotation object.
 *
 * TesterPlugin classes define lists of URLs that are generated by their
 * related modules.
 *
 * @Annotation
 */
class TesterPlugin extends Plugin {

  /**
   * A unique identifier for the tester plugin.
   *
   * @var string
   */
  public $id;

}
