<?php

/**
 * Implements hook_page_top().
 *
 * In this function, we insert deliberate errors under some conditions.
 */
function tester_error_generator_page_top(&$page_top) {
  // Get the current request path.
  $path = \Drupal::request()->getPathInfo();

  if ($path === '/') {
    $text = tester_error_generator_throw_warning();
  }

  else {
    $number = rand(1, 5);
    switch ($number) {
      case 1:
        $text = tester_error_generator_throw_notice();
        break;

      case 2:
        $text = tester_error_generator_throw_error();
        break;

      case 3:
        $text = tester_error_generator_throw_deprecated();
        break;

      default:
        $text = 'This module should not be used in production';
        break;
    }
  }

  return $page_top['tester'] = [
    '#prefix' => '<div class="messages messages--status">',
    '#markup' => $text,
    '#suffix' => '</div>',
  ];
}

/**
 * Generates an E_WARNING.
 *
 * @return string
 *   A message string.
 */
function tester_error_generator_throw_warning() {
  return 'Generating a warning';
}

/**
 * Generates an E_NOTICE.
 *
 * @return string
 *   A message string.
 */
function tester_error_generator_throw_notice() {
  return 'Generating a notice';
}

/**
 * Generates an E_RECOVERABLE_ERROR.
 *
 * @return string
 *   A message string.
 */
function tester_error_generator_throw_error() {
  return 'Generating an error';
}

/**
 * Generates an E_DEPRECATED.
 *
 * @return string
 *   A message string.
 */
function tester_error_generator_throw_deprecated() {
  return 'Generating a deprecation';
}
